### ISSUE TITLE
Can't run test suite

### ISSUE THREAD

**Issue by minchinweb** [ciur/papermerge-worker#2]
I'm trying to check out *papermerge*, but I can't get it to upload anything. I've traced my problem back here, so I thought I'd try the test suite here, but it errors out trying to set up a socket for logging.

Here is the traceback trying to run `./test/run.py`:

```
λ python .\test\run.py
Traceback (most recent call last):
  File "C:\Python38\lib\logging\config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "C:\Python38\lib\logging\config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "C:\Python38\lib\logging\handlers.py", line 821, in __init__
    self._connect_unixsocket(address)
  File "C:\Python38\lib\logging\handlers.py", line 853, in _connect_unixsocket
    self.socket = socket.socket(socket.AF_UNIX, use_socktype)
AttributeError: module 'socket' has no attribute 'AF_UNIX'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\test\run.py", line 18, in <module>
    setup_logging()
  File "e:\code\papermerge-worker\pmworker\__init__.py", line 48, in setup_logging
    logging.config.dictConfig(config)
  File "C:\Python38\lib\logging\config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Python38\lib\logging\config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'syslog'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python38\lib\logging\__init__.py", line 2115, in shutdown
    h.close()
  File "C:\Python38\lib\logging\handlers.py", line 892, in close
    self.socket.close()
AttributeError: 'SysLogHandler' object has no attribute 'socket'
```

I'm on Windows 10, with Python 3.8.4. I suspect this error is from trying to set up a Unix socket on a Windows system.

I don't have any configuration file (for either this or *papermerge* proper), so this on the defaults.

Also, why does this project look for a configuration files in the `/etc/briolette/` directory ([here](https://github.com/ciur/papermerge-worker/blob/e451daf980327a90b110c47fb1611b9555ae3222/pmworker/__init__.py#L37))? I don't recall seeing that in the documentation anywhere.

**Comment by ciur** [comment]
Hi,
There is an important thing. 
Papermerge worker is **seriously outdated**.
It is so, because since April 2020 I was focusing mostly on simplifying initial setup and make main app work with [built-in
 worker.](https://papermerge.readthedocs.io/en/latest/utilities.html#worker).
Once I am done with [version 1.4.0 release ](https://github.com/ciur/papermerge/issues/36#issuecomment-657230471)(which is one host centred) I will update pmworker.
